-- Runs as APP_USER (cal) on first container init.
-- gvenzl image places this user-scoped script after the user is created.

CREATE TABLE meetings (
  id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  client_name   VARCHAR2(200) NOT NULL,
  title         VARCHAR2(300),
  starts_at     TIMESTAMP NOT NULL,
  ends_at       TIMESTAMP NOT NULL,
  notes         CLOB,
  image_blob    BLOB,
  image_mime    VARCHAR2(100),
  google_event_id VARCHAR2(200),
  created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX idx_meetings_starts ON meetings (starts_at);

-- single-row token store for Google OAuth (push sync)
CREATE TABLE google_tokens (
  id            NUMBER DEFAULT 1 PRIMARY KEY,
  access_token  VARCHAR2(2000),
  refresh_token VARCHAR2(2000),
  expiry        NUMBER,
  CONSTRAINT chk_single_row CHECK (id = 1)
);
