-- Auth + multi-tenant migration. Idempotent-ish (run once).

CREATE TABLE accounts (
  id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  username      VARCHAR2(100) NOT NULL,
  password_hash VARCHAR2(200) NOT NULL,
  role          VARCHAR2(20)  NOT NULL,           -- 'ADMIN' | 'CLIENT'
  name          VARCHAR2(200) NOT NULL,           -- display / company name (ex: HSBC)
  active        NUMBER(1) DEFAULT 1 NOT NULL,
  created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_accounts_username UNIQUE (username),
  CONSTRAINT chk_accounts_role CHECK (role IN ('ADMIN', 'CLIENT'))
);

-- each meeting belongs to a CLIENT account (the company whose agenda it shows)
ALTER TABLE meetings ADD (client_id NUMBER);
ALTER TABLE meetings ADD CONSTRAINT fk_meetings_client
  FOREIGN KEY (client_id) REFERENCES accounts(id);

CREATE INDEX idx_meetings_client ON meetings (client_id);
